### ISSUE TITLE
Devcontainer not compiling

### ISSUE THREAD

**Issue by han-so1omon** [ingenierias-lentas/recopiladora#10]
**Describe the bug**
Devcontainer is not compiling via Devpod

**To Reproduce**
1. Go to Devpod
2. Create workspace -> Point to project root directory and .devcontainer/devcontainer.json file
3. Set environment to Docker & Open With VSCode
4. Open with VSCode

**Expected behavior**
Expected to open with VSCode

**Screenshots**
<img width="1197" alt="Screenshot 2024-09-04 at 2 51 57 PM" src="https://github.com/user-attachments/assets/f0e8eea9-7d90-4c38-8338-099cae377554">

**Desktop (please complete the following information):**
 - OS: MacOS

**Additional context**
Possibly related issue...
https://github.com/devcontainers/features/issues/831

**Comment by han-so1omon** [comment]
@msolorio Here are my intermittent updates with devcontainers from today. Feel free to look through, else I'll get back to it tomorrow

**Comment by msolorio** [comment]
Following the steps to reproduce (set file path to local repo), I was able to have the DevContainer compile and open vscode.

![Screenshot 2024-09-05 at 9 57 22 AM](https://github.com/user-attachments/assets/8e67031f-4f07-43c2-89e3-644eb5ca44ba)
![Screenshot 2024-09-05 at 9 57 54 AM](https://github.com/user-attachments/assets/6d175469-fd2e-45a2-b552-68b89af9106a)
![Screenshot 2024-09-05 at 9 59 19 AM](https://github.com/user-attachments/assets/5f0680a7-c402-4c3f-9320-ed47a6d6bba9)

**Comment by han-so1omon** [comment]
@msolorio What laptop are you using?

**Comment by msolorio** [comment]
Using OS: macOS Sonoma 14.1.1

**Comment by han-so1omon** [comment]
Interesting, I'm on Sonoma 14.6

**Comment by msolorio** [comment]
I'm on the intel chip

**Comment by han-so1omon** [comment]
Ah, I'm on the Apple Silicon

**Comment by msolorio** [comment]
https://github.com/docker/for-mac/issues/7006#issuecomment-2124954348

**Comment by han-so1omon** [comment]
@msolorio Solved by upgrading to Docker Desktop 4.33. Now using 4.34 and it still works
